# Generated by Django 4.2 on 2023-06-11 17:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='account',
            name='image',
            field=models.CharField(blank=True, max_length=400, null=True, verbose_name='Image'),
        ),
    ]
