# Generated by Django 4.2.5 on 2025-05-02 22:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_account_last_viewed_concept_videos_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='NavbarButton',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(choices=[('about', 'About'), ('ace_jee', 'Ace-JEE'), ('jee_mains', 'JEE Mains'), ('jee_advanced', 'JEE Advanced'), ('ace_neet', 'Ace-NEET')], max_length=50, unique=True)),
                ('display_name', models.CharField(max_length=50)),
                ('is_enabled', models.BooleanField(default=True)),
                ('order', models.IntegerField(default=0)),
                ('parent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='children', to='users.navbarbutton')),
            ],
            options={
                'ordering': ['order'],
            },
        ),
    ]
