# Generated by Django 4.2.5 on 2025-05-02 22:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_navbarbutton'),
    ]

    operations = [
        migrations.CreateModel(
            name='VideoCard',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tab', models.CharField(choices=[('Newest', 'Newest'), ('Popular', 'Popular'), ('Active', 'Active')], max_length=10)),
                ('title', models.CharField(max_length=200)),
                ('subtitle', models.CharField(max_length=200)),
                ('video_url', models.URLField()),
            ],
        ),
    ]
