# Generated by Django 4.2.5 on 2025-05-02 23:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0006_examcard'),
    ]

    operations = [
        migrations.CreateModel(
            name='QuestionCard',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question_text', models.CharField(max_length=255)),
                ('question_subtext', models.TextField(blank=True)),
                ('image', models.ImageField(upload_to='question_images/')),
                ('tabs', models.CharField(choices=[('JEE-Mains', 'JEE-Mains'), ('JEE-Advanced', 'JEE-Advanced'), ('NEET', 'NEET')], max_length=20)),
            ],
        ),
    ]
