# Generated by Django 4.2 on 2023-05-30 09:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_alter_user_managers_remove_user_isadmin_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='provider',
            field=models.CharField(default='CredentialsProvider', max_length=30),
        ),
        migrations.AlterField(
            model_name='user',
            name='provider_account_id',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
    ]
