# Generated by Django 4.2 on 2023-06-04 14:09

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_alter_user_access_token_alter_user_contact_no_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='recently_visited_concept_videos',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.IntegerField(), blank=True, default=[0, 0], null=True, size=None),
        ),
        migrations.AddField(
            model_name='user',
            name='recently_visited_questions',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.IntegerField(), blank=True, default=[0, 0], null=True, size=None),
        ),
    ]
