# Generated by Django 4.2 on 2023-06-18 02:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('question', '0004_comment'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='comment',
            options={},
        ),
    ]
