# Generated by Django 4.2 on 2023-06-23 13:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('question', '0007_alter_tag_name'),
        ('question', '0009_alter_comment_commenter'),
    ]

    operations = [
    ]
