# Generated by Django 4.2 on 2023-07-02 07:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('question', '0011_alter_comment_commenter'),
    ]

    operations = [
        migrations.CreateModel(
            name='Examination',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slug', models.CharField(max_length=50, unique=True)),
                ('name', models.CharField(max_length=300, unique=True)),
            ],
        ),
        migrations.AddField(
            model_name='question',
            name='exam',
            field=models.ManyToManyField(to='question.examination'),
        ),
    ]
