# Generated by Django 4.2 on 2023-07-03 08:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('question', '0012_examination_question_exam'),
    ]

    operations = [
        migrations.RenameField(
            model_name='question',
            old_name='exam',
            new_name='examinations',
        ),
        migrations.RemoveField(
            model_name='examination',
            name='slug',
        ),
        migrations.AlterField(
            model_name='examination',
            name='name',
            field=models.CharField(max_length=255),
        ),
    ]
