# Generated by Django 4.2 on 2023-07-04 22:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('question', '0013_rename_exam_question_examinations_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='question',
            name='question_text_latex',
            field=models.TextField(blank=True, null=True),
        ),
    ]
