# Generated by Django 4.2 on 2023-04-23 01:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0002_question'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='question',
            name='created_by',
        ),
    ]
