# Generated by Django 4.2 on 2023-05-24 04:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0004_delete_question_remove_user_username_user_contact_no_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('A', 'Admin'), ('M', 'Manager'), ('P', 'Premium User'), ('G', 'General User')], default='G', max_length=1),
        ),
    ]
